name: Test
on:
  push:
  schedule:
    - cron: '0 11 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install flutter dependencies
        run: |
          ./tool/install.sh
      - name: Run tests
        run: |
          ./tool/setup.sh
          source ./tool/env.sh
          flutter analyze
          flutter test
