name: Test
on:
  push:
  schedule:
    - cron: '0 11 * * *'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Cache pub modules
        uses: actions/cache@v1
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-
      - name: Install flutter dependencies
        run: |
          ./tool/install.sh
      - name: Run tests
        run: |
          ./tool/setup.sh
          source ./tool/env.sh
          flutter analyze
          flutter test
      - name: Run driver tests
        if: runner.os == 'macOS'
        run: |
          source ./tool/env.sh
          xcrun simctl boot "iPhone 8"
          flutter drive --target=test_driver/main.dart
